# version removed to avoid warning

services:
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
